### ISSUE TITLE
Sometimes headcount is -1

### ISSUE THREAD

**Issue by morkor** [worldbank/povcalnetR#20]
try:
povcalnet("GNB",10,1991)
gives: -1 to headcount povertygap povertygapsq watts
it should give 1 to headcount at least

**Comment by tonyfujs** [comment]
Thanks for reporting this @morkor 
You're right. This is an issue with the underlying povcalnet API, not the R package itself (But since the povcalnet API itself is not open-source yet, this Github repo is the right place to report those issues).

* -1 means that the request could not be computed successfully, and the result is missing. This should be made clearer in the PovcalnetR wrapper, and -1 should be recoded as missing. I will create a separate issue for that.
* For the more substantial issue of the headcount value. I will take a look at the povcalnet codebase and see how this can be addressed in a future release.

**Comment by morkor** [comment]
now that I am thinking of it, it may also be specific to GNB1991 because it is the only distribution for which there are no data above a poverty line of 5.68 for some reason.
